on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: WORKAROUND delete top-level package.json
        run: rm package.json

      - name: Set up pnpm
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          working-directory: inner-uses-12-0-0